spring:
  application:
    name: orderhub

  datasource:
    url: jdbc:mysql://localhost:3306/orderhub_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: "orderhub-secret-key-for-development-only-must-be-at-least-32-characters"
    expiration-ms: 86400000